### ISSUE TITLE
Feat: Add hypixel support

### ISSUE THREAD

**Issue by Blocksnmore** [EinsLucaaa/AutoGG#2]
**Is your feature request related to a problem? Please describe.**
The autogg addon doesn't support hypixel in sending gg at the end of rounds

**Describe the solution you'd like**
Adding the ability for autogg to trigger on hypixel

**Describe alternatives you've considered**
Using Sk1er's autogg mod or laby autotext (disabled on hypixel)

**Additional context**
If regex is supported you could probably just use the [detection autogg uses](https://static.sk1er.club/autogg/regex_triggers_3.json)

**Comment by EinsLucaaa** [comment]
Hypixel support was added with version 1.0.3 (https://github.com/EinsLucaaa/AutoGG/releases/tag/1.0.3) and is now also available via LabyMod. Thank you for the suggestion and your patience.
